lidar_topic: /hesai/pandar
IMU_topic: /alphasense/imu
Lidar_front_end:
   lidar_type: 4   # 1 enum LID_TYPE{MID=0,HORIZON=1,VELO16=2,OUST64=3,QT64=4};
   point_skip: 1
   blind: 0.5  #* exp16_attic_to_upper_gallery_2 exp18_corridor_lower_gallery_2 需要设置为1.0，不然人身上的点太多

poslam_lio:
   dense_map_enable: true # false  true
   num_match_pts: 5 # kd树搜索的点数量
   max_iteration: 3           # Maximum times of LIO esikf.  增大好像没什么用
   filter_size_map: 0.5 #* kd树下采样 0.50
   voxel_downsample_size_surf: 0.5 #* 点云下采样
   lidar_cov_p: 1.02  # 0.025
   # 1.015 0.06261218564948377
   # 1.02 0.040034576320136524
   # 1.025 0.07816755014938105
   # 1.03 0.0989025916410205
   lidar_to_imu_R:
      [0., -1.,  0.,
      -1.,  0., 0.,
      0.,  0., -1.]
   lidar_to_imu_t: [-0.001, -0.00855, 0.055]
   lio_pts_num: 1600.0 # 前端下采样之后的点数量（暂时不用）
   use_backend: true # false  true
   plane_merge_angle: 8 # 小平面融合的最大角度
   # plane_merge_angle: 3 # 小平面融合的最大角度
   plane_merge_dist: 0.015 # 小平面合并的最大距离(中心点到平面)
   max_eigen_dist_th: 0.05 # 构成平面最大特征值的最小值 
   max_merge_plane_n: 16 # 每个融合平面的最大小平面数量 (为16还可以)
   min_plane_pts_n: 15 # 每个网格拟合平面的最小点数量 (默认50) 15
   pi_split_n: 45 # 180度划分的份数
   # : 600  # 延迟搜索树延迟的帧数量
   P_r_value: 1.0 #* 回环帧位姿误差信息矩阵的值
   error_scale: 0.01 #* 回环优化中点面约束和平面约束的权重比值
   use_pl_lio: true # false  true 是否使用平面前端
   use_non_plane_pt: true # false  true 是否在平面前端中使用非平面点
   large_scale_env: false
   process_debug: false # false  true 输出代码运行位置