lidar_topic: /livox/lidar
IMU_topic: /livox/imu
Lidar_front_end:
   lidar_type: 1   # 1 enum LID_TYPE{MID=0,HORIZON=1,VELO16=2,OUST64=3,QT64=4};
   point_skip: 1
   blind: 1.5

poslam_lio:
   dense_map_enable: 1
   num_match_pts: 5 # kd树搜索的点数量
   max_iteration: 3           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_map: 0.50 #* kd树下采样 0.50
   voxel_downsample_size_surf: 0.1 #* 点云下采样
   lidar_to_imu_R:
      [1., 0.,  0.,
      0.,  1., 0.,
      0.,  0., 1.]
   lidar_to_imu_t: [0.04165, 0.02326, -0.0284]
   lio_pts_num: 800.0 # 前端下采样之后的点数量（暂时不用）
   use_backend: true # false  true
   large_scale_env: false